init_elements()
z.A = point(0, 0)
z.B = point(1.5, -3)
z.C = point(4, 1)
T.ABC = triangle(z.A, z.B, z.C)
C.ABC = T.ABC:circum_circle()
z.w, z.t = C.ABC:get()
z.P = C.ABC:point(-0.15)
L.steiner = T.ABC:steiner_line(z.P)
z.sa, z.sb = L.steiner:get()
z.H = T.ABC.orthocenter
CO.PA = conic:new(z.P, L.steiner, 1)
PA.curve = CO.PA:points(-5, 5, 50)
z.M = intersection(CO.PA, T.ABC.ca)
